--- 
title: "Dashboarding s paketom Shiny"
author: "Jana Faganeli Pucer, Patrik Kojanec, Matej Pičulin in Erik Štrumbelj"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: patrik-kojanec/dashboarding_v_Shiny_R
description: "Gradivo za delavnico Dashboarding s paketom Shiny pobude DataScience@UL-FRI."
nocite: | 
  @Wickham2014, @Wickham2016
---

# Uvod {-}

## Motivacija {-}
Neobdelani podatki so običajno preveč obsežni, da bi iz njih lahko hitro razbrali vse informacije. Takšne podatke zato običajno povzamemo z opisnimi statistikami (povprečja, razponi) in jih prikažemo s pomočjo grafov ali tabel. Takoj, ko želimo to storiti, pa se pojavi težava: kateri povzetek je najbolj primeren za naše podatke? Katere metrike so najbolj pomembne in razumljive za naše ciljne uporabnike? Kaj pa, če jih zanima deset ali več metrik? Kako bi jih smiselno združili v eno samo poročilo? Veliko povzetkov bi podaljšalo poročilo, vsi povzetki na enem samem grafu ali v eni sami tabeli, pa bi bili nepregledni. 

S statičnimi povzetki torej težko pregledamo in na en mah zajamemo vse pomembne informacije. Kot rešitev teh omejitev so se razvila orodja, ki slonijo na **kontrolnih ploščah** (angl. *dashboard*, izraz, ki ga bomo uporabljali v tej delavnici). Ta orodja temeljijo na kompromisu med preglednostjo in fleksibilnostjo prikaza. Uporabniku prikažemo manjše število povzetkov, ki pa so interaktivni in uporabniku omogočajo, da si jih prilagodi.

Dashboard-i so tematika te delavnice. Spoznali bomo paket **Shiny R**, ki nam omogoča, da s pomočjo programskga jezika R ustvarimo dashboard-e v obliki interaktivnih spletnih aplikacij. Ob koncu delavnice bomo znali ustvariti svoj dashboard, kot je na primer [ta](https://delavnice-datascience.shinyapps.io/dn_3/). 

## Struktura te knjige {-}
Vsako poglavje ima 3 sklope:

1) **Priprava.** Ta sklop je namenjen temu, da se udeleženci pripravijo na predavanje. Ker bodo le-ta intenzivna in namenjena predstavitvi glavnih konceptov ter uporabi funkcij na praktičnih primerih, je dobro, da poznamo osnovne klice uporabljenih funkcij. V pripravi si bomo na preprostih podatkih pogledali, kako izvajati osnovne klice funkcij v tidyverse. Za vsako pripravo je na voljo video. Priprava traja največ 30 minut.

2) **Jedro.** V tem sklopu je zajeta vsebina posameznega predavanja in včasih dodatna snov, ki jo predelamo samostojno. Podrobneje opišemo posamezne koncepte in funkcije ter demonstriramo na praktičnih primerih.

3) **Domača naloga.** Na koncu vsakega predavanja so vaje za utrjevanje. Poskusimo jih rešiti sami. V tej knjigi bodo prikazani samo rezultati rešitev brez postopka oziroma programske kode. V kolikor se nam zatakne, lahko preverimo rešitev v izvornih datotekah Rmd, ki se nahajajo na repozitoriju. Nekatere naloge od nas zahtevaj, da kaj raziščemo sami, z uporabo vgrajene pomoči ali spleta, kot smo to navajeni pri vsakodnevnem programerskem delu. Domača naloga vsakega sklopa je sestavljena iz nekaj osnovnih nalog, ki ponovijo snov predavanj. Poleg teh pa so tudi težje naloge, pri kateri je potrebno koncepte uporabiti na realni podatkovni množici ali samostojno rešiti probleme, ki jih na predavanju ne bomo predelali.

```{r echo = FALSE}
knitr::opts_chunk$set(
  error = TRUE, # do not interrupt in case of errors
  warnings = FALSE,
  message = FALSE
)
```

